#!/usr/bin/env python3

import sys
import os

script_dir = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(0, script_dir)

import slack

if __name__ == "__main__":
    slack.main(sys.argv[1:])